---
title: Great Food Buddie
emoji: 🍽️
colorFrom: indigo
colorTo: pink
sdk: streamlit
sdk_version: "1.45.1"
app_file: app.py
pinned: false
---
Check out the configuration reference at https://huggingface.co/docs/hub/spaces-config-reference
